export const countryRegex = [
	["Italy", "Italian", "Rome", "Roman"],
	["France", "French"],
	["UK", "British", "England", "Britain", "English"],
	["Sweden", "Swedish"],
	["Spain", "Spanish"],
	["Germany", "German"],
	["USA", "American", "United States", "America", "US"],
	["Celebes"],
	["Iran", "Persian", "Iranian"],
	["Qatar", "Qatarian"],
	["Syria", "Syrian"],
	["Gambia", "Gambian"],
	["Sahalin"],
	["Moldova", "Moldovian"],
	["China", "Chinese"],
	["Burma", "Burmian"],
	["Rwanda", "Rwandian"],
	["Oman", "Omanian"],
	["Somalia", "Somalian"],
	["Albania", "Albanian"],
	["Tunisia", "Tunisian"],
	["Chile", "Chileno"],
	["Iceland", "Icelandic"],
	["Lithuania", "Lithuanian"],
	["El Salvador", "El Salvadorian"],
	["Turkey", "Turkish"],
	["India", "Indian"],
	["Japan", "Japanese"],
	["Sudan", "Sudanese"],
	["Portugal", "Portuguese"],
	["Mozambique"],
	["Slovakia", "Slovakian"],
	["South Korea", "South Korean"],
	["Libya", "Libyan"],
	["Russia", "Russian"],
	["Niger"],
	["Lesotho"],
	["Cambodga", "Cambodian"],
	["Ethiopia", "Ethiopian"],
	["Yemen"],
	["Sierra Leone"],
	["Guatemala", "Guatemalian"],
	["Liberia", "Liberian"],
	["Norway", "Norwegian"],
	["Bali"],
	["Equador", "Equadorian"],
	["Finland", "Finnish"],
	["Romania", "Romanian"],
	["Swaziland"],
	["Burkina"],
	["Flores"],
	["Benin"],
	["Cote Divoire"],
	["Guyana"],
	["Tagikistan"],
	["Bosnia", "Bosnian"],
	["Ukraine", "Ukrainian"],
	["Belarus", "Belarussian"],
	["Brumnei"],
	["Zimbabwe"],
	["Ireland", "Irish"],
	["Venezuela", "Venezuelan"],
	["Panama"],
	["Eguat Guinea"],
	["Argentina", "Argentinian"],
	["Sahara"],
	["Congo", "Congolese"],
	["Zambia"],
	["Turkey", "Turkish"],
	["Haiti", "Haitian"],
	["South Africa", "South African"],
	["Armenia", "Armenian"],
	["Egypt", "Egyptian"],
	["Guinea", "Guinean"],
	["Camerun"],
	["Uzbekistan"],
	["Hungary", "Hungarian"],
	["Vietnam", "Vietnamese"],
	["Serbia", "Serbian"],
	["Denmark", "Danish"],
	["Mali"],
	["Taiwan", "Taiwanese"],
	["Belize"],
	["Bolivia", "Bolivian"],
	["Lithuania", "Lithuanian"],
	["Austria", "Austrian"],
	["Senegal"],
	["Nigeria", "Nigerian"],
	["Iraq", "Iraqi"],
	["Bangladesh"],
	["Czech"],
	["Saudi Arabia"],
	["Mautitania"],
	["Tanzania"],
	["Paraguay"],
	["Kuwait"],
	["Arctica"],
	["New Zealand"],
	["Greenland"],
	["Cuba", "Cuban"],
	["Poland", "Polish"],
	["Jamaica", "Jamaican"],
	["Ecuador", "Ecuadorian"],
	["Lebanon"],
	["Costa Rica"],
	["Chad"],
	["Nicaragua"],
	["Brazil", "Brazilian"],
	["Slovenia", "Slovenian"],
	["Latvia", "Latvian"],
	["Morocco", "Moroccan"],
	["Bulgaria", "Bulgarian"],
	["Zambia", "Zambian"],
	["Botswana"],
	["Dominican Republic"],
	["Uganda", "Ugandan"],
	["Israel", "Israelian"],
	["Argentina", "Argentinian"],
	["Kenya"],
	["Thailand", "Thai"],
	["Pakistan"],
	["Australia", "Australian"],
	["Singapore", "Singaporean"],
	["UAE"],
	["Netherlands", "Dutch"],
	["Kazakhstan"],
	["Laos"],
];

export const categoryRegex = {
	war: [
		'War',
		'Siege',
		'Battle',
		'Treaty',
		'raid',
		'surrender',
		'force',
		'conflict',
		'troops',
		'invasion',
		'military',
		'warfare',
		'armistice',
		'skirmish',
		'ceasefire',
		'defeat',
		'capture',
		'crusade',
	],
	science: [
		'discovery',
		'research',
		'experiment',
		'research',
		'breakthrough',
		'scientific',
		'innovation',
		'invention',
		'exploration',
		'hytothesis',
		'laboratory',
		'technology',
		'software',
	],
	disaster: [
		'disaster',
		'catastrophe',
		'emergency',
		'evacuation',
		'rescue',
		'devastation',
		'calamity',
		'tragedy',
		'earthquake',
		'tsunami',
		'desctruction',
	],
	politics: [
		'Coronation',
		'politician',
		'parliament',
		'court',
		'sign',
		'crowned',
		'marries',
		'marriage',
		'peace',
		'succeed',
		'elevated',
		'council',
		'policy',
		'government',
		'governor',
		'president',
		'independence',
		'election',
		'elected',
		'legislation',
		'summit',
		'diplomat',
		'governance',
		'negotiation',
	],
	entertainment: [
		'performance',
		'concert',
		'premiere',
		'film',
		'entertainment',
		'celebrity',
		'festival',
		'exhibition',
		'celebration',
	],
	sports: [
		'game',
		'tournament',
		'athlete',
		'championship',
		'record',
		'competition',
		'league',
	],
	health: [
		'medical',
		'health',
		'disease',
		'outbreak',
		'epidemic',
		'vaccine',
		'treatment',
		'pandemic',
		'cancer',
	],
	economy: [
		'company',
		'tax',
		'pay',
		'economy',
		'corporation',
		'business',
		'enterprise',
		'aquisition',
		'conglomerate',
		'industry',
		'trade',
		'invest',
		'financial',
	],
	religion: [
		'religi',
		'church',
		'pope',
		'priest',
		'cardinal',
		'christian',
		'catholic',
		'protestant',
		'orthodox',
		' st ',
		'bible',
		'cathedral',
		'mosque',
		'synagogue',
		'hindu',
		'jew',
		'islam',
		'buddh',
		'judaism',
	],
};

export const spline_list = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Antarctica', 'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bali', 'Bangladesh', 'Belgium', 'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Borneo',
    'Bosnia', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi', 'Gambia', 'Cambodia',
    'Cameroon', 'Canada', 'Celebes', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Congo',
    'Costa Rica', 'CoteDivoire', 'Crime', 'Croatia', 'Cuba', 'Czech', 'Democratic Republic of Congo', 'Denmark',
    'Dill', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea',
    'Estonia', 'Ethiopia', 'Falkland', 'Finland', 'Flores', 'France', 'French Guyana', 'Gabon', 'Georgia', 'Germany',
    'Ghana', 'Greece', 'Greenland', 'Guatemala', 'Guinea', 'Guinea Bissau', 'Guyana', 'Haiti', 'Holman', 'Hungary',
    'Iceland', 'India', 'Iraq', 'Iran', 'Ireland', 'Islands', 'Israel', 'Italy', 'Jakarta', 'Jamaica', 'Japan', 'Jordan',
    'Kazakhstan', 'Kenya', 'Kos', 'Kuala Lumpur', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
    'Libya', 'Lithuania', 'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mexico', 'Moldova', 'Mongolia', 'Mont', 'Morocco',
    'Mozambique', 'Namibia', 'Nepal', 'Netherlands','New Guinea', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
    'North Korea', 'Norway', 'Oman', 'Pakistan', 'Palawan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Phnom Penh',
    'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Sahalin', 'Saudi Arabia', 'Senegal', 'Serbia',
    'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain',
    'Sudan', 'Sumba', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Taiwan', 'Tanzania',
    'Tasmania', 'Thailand', 'Tierra del Fuego', 'Togo', 'Tunisia', 'Turkey', 'Turkmenistan', 'UAE', 'Uganda', 'UK',
    'Ukraine', 'Uruguay', 'USA', 'Uzbekistan', 'Venezuela', 'Vietnam', 'Western Sahara', 'Yemen', 'Ytennane', 'Zambia',
    'Zimbabwe'
  ];